# используем язык java. Travis CI поддерживает другие языки тоже.
language: java
jdk:
  - openjdk14

# используем режим обычного пользователя для сборки проекта.
sudo: false

# после выполнения сборки запустить скрипт, который будет собирать статистику по JaCoCo
# Здесь используется сторонний сервис https://codecov.io/
after_success:
  - bash <(curl -s https://codecov.io/bash)

# Отправлять уведомление на почту tel.89194491005.usp@gmail.com (Изменить на свою) если сборка упала
notifications:
  email:
    recipients:
      - tel.89194491005.usp@gmail.com
    on_success: never # default: change
    on_failure: always # default: always
env:

  global:

    - CODECOV_TOKEN="788e1a6a-17fa-49fe-b920-cd7efd7ef1fd"